name: Cypress happy path

on:
  push:
    branches:
      - main

jobs:
  happypath:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/e2e/happyPath.cy.ts
          build: npm run build
          start: npm run dev
